name = "xtracombo"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

account_id = "f5cdc2b42a68f8bd8b54eefa09bc4802"
workers_dev = true

[[kv_namespaces]]
binding = "XTRACOMBO"
id = "b7c25afec1ca4d21b35a484200772bb8"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "ccccccc1-bbbb-4aaa-addd-aaaaaaaaaaa1"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/XtraCombo/Marina/refs/heads/main/web/index.html"
SUBLINK_PAGE_URL = "https://raw.githubusercontent.com/XtraCombo/Marina/refs/heads/main/web/sublink.html"
